apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxianalytics
  labels:
    app: taxianalytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taxianalytics
  template:
    metadata:
      labels:
        app: taxianalytics
    spec:
      containers:
      - name: taxianalytics
        image: $DOCKER_IMAGE_TAG
        # We are using a local image here
        imagePullPolicy: Never
        env:
        - name: GCLOUD_KEY
          value: '$GCLOUD_KEY'
        - name: TAXI_TOPIC
          value: $TAXI_TOPIC
        - name: TAXI_PROJECT
          value: $TAXI_PROJECT
        - name: DB_HOST
          value: $DB_HOST
        ports:
        - containerPort: 8080